sudo: required
dist: trusty
language: node_js
after_success: npm run coverage && cat ./coverage/lcov.info | coveralls

env:
  matrix:
    - NODE_VERSION="4" NPM_VERSION="3"
    - NODE_VERSION="5" NPM_VERSION="3"
    - NODE_VERSION="5" NPM_VERSION="3"
    - NODE_VERSION="6" NPM_VERSION="3"
    - NODE_VERSION="6" NPM_VERSION="4"
    - NODE_VERSION="7" NPM_VERSION="3"
    - NODE_VERSION="7" NPM_VERSION="4"

addons:
  # From some tests it seems you can only have one firefox addon.
  # Adding two results in the last one defined being the one installed.
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

script:
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=mqVTe91nICY38tHlFFtmZIjbzpghGZyos
  - cd core
  - npm install .
  - npm run coverage
  - cd ..
  - cd cli
  - mkdir -p tmp
  - cd tmp
  - npm init -f
  - npm install ..
  - ../runTestsLocal.sh
  - cd ..
  - npm install . -g
  - npm run coverage
  - ./runTests.sh
before_install:
  - sudo apt-get update -qq
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
  - source ~/.nvm/nvm.sh && nvm install $NODE_VERSION && nvm use $NODE_VERSION
  # Build Tools
  - npm install -g npm@$NPM_VERSION
  # Show environment info
  - node --version
  - npm --version
before_script:
  - npm install -g jshint
  - npm install -g istanbul
  - npm install -g istanbul-coveralls
  - npm install -g nodeunit
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f3499197be7208e15199
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
