sudo: required
dist: trusty
language: node_js
after_success: npm run coverage && cat ./coverage/lcov.info | coveralls

env:
  matrix:
    - NODE_VERSION="4" NPM_VERSION="3" DISPLAY=:99
    - NODE_VERSION="5" NPM_VERSION="3" DISPLAY=:99
    - NODE_VERSION="5" NPM_VERSION="3" DISPLAY=:99
    - NODE_VERSION="6" NPM_VERSION="3" DISPLAY=:99
    - NODE_VERSION="6" NPM_VERSION="4" DISPLAY=:99
    - NODE_VERSION="7" NPM_VERSION="3" DISPLAY=:99
    - NODE_VERSION="7" NPM_VERSION="4" DISPLAY=:99

services:
  - docker

addons:
  # From some tests it seems you can only have one firefox addon.
  # Adding two results in the last one defined being the one installed.
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta
cache:
  directories:
    - "node_modules"

script:
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=mqVTe91nICY38tHlFFtmZIjbzpghGZyos
  - ./docker-build-images.sh
  - cd core
  - npm install .
  - npm run coverage
  - cd ..
  - cd cli
  - mkdir -p tmp
  - cd tmp
  - npm init -f
  - npm install ..
  - ../runTestsLocal.sh
  - cd ..
  - npm install . -g
  - npm run coverage
  - ./runTests.sh
before_install:
  # Prepare node and npm
  - nvm install $NODE_VERSION && nvm use $NODE_VERSION
  - npm install -g npm@$NPM_VERSION
  # Show environment info
  - node --version
  - npm --version
before_script:
  - npm install -g jshint
  - npm install -g istanbul
  - npm install -g istanbul-coveralls
  - npm install -g nodeunit
  - "sh -e /etc/init.d/xvfb start"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f3499197be7208e15199
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
